### ISSUE TITLE
cant open https://zhuxiaotan.xyz/self-driving-project/

### ISSUE THREAD

**Issue by olyii** [SugarmanZhu/Self-Driving-Project#1]
help me

**Comment by SugarmanZhu** [comment]
I'm sorry the link doesn't work.  You may locate the CARLA files at [this Google Drive link](https://drive.google.com/drive/folders/101f_7jeTivCd6d38idCvvZD0b5TD6sxV?usp=sharing).

**Comment by olyii** [comment]
> I'm sorry the link doesn't work. You may locate the CARLA files at [this Google Drive link](https://drive.google.com/drive/folders/101f_7jeTivCd6d38idCvvZD0b5TD6sxV?usp=sharing).

how can i find "method PurePursuit"and "method stanley"code?

**Comment by SugarmanZhu** [comment]
You can implement those methods in the controller file.
